apiVersion: fortiwebingress.io/v1
kind: FortiWebIngress
metadata:
  name: gateway
  namespace: fortiweb-controller
spec:
  fortiweb:
    address: "10.0.10.100:8443"
    credentialsSecret: fortiweb-credentials
    # credentialsSecretNamespace: fortiweb-controller  # defaults to CR namespace

  virtualServer:
    name: gateway
    ip: "10.0.1.100"
    interface: port1
    useInterfaceIP: true

  policy:
    name: gateway-policy
    webProtectionProfile: "Inline Standard Protection"
    httpService: "HTTP"
    httpsService: "HTTPS"
    synCookie: "enable"
    httpToHttps: "disable"

  routes:
    - host: app1.example.com
      path: /
      backend:
        serviceName: frontend
        serviceNamespace: app1
        port: 80

    - host: app2.example.com
      path: /
      backend:
        serviceName: backend
        serviceNamespace: app2
        port: 8080
